version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./Client/:/usr/src/app
      - /usr/src/app/node_modules
  node-app:
    image: node-app
    env_file: ./Auth/.env
    ports:
      - "8080:8080"
    networks:
      - mern-app
    volumes:
      - ./Auth/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
