version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./Client/:/usr/src/app
      - /usr/src/app/node_modules
  node-app:
    image: node-app
    env_file: ./Auth/.env
    ports:
      - "8000:8000"
    networks:
      - mern-app
    volumes:
      - ./Auth/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    
  
  cache_service:
    build: ./cache/.
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - cache-mongodb
    networks:
      - mern-app

  cache-mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27018:27018
    networks:
      - mern-app
      
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local