apiVersion: v1
kind: Service
metadata:
  name: cache-app-service
spec:
  selector:
    app: cache-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-app
  template:
    metadata:
      labels:
        app: cache-app
    spec:
      containers:
        - name: cache-app
          image: dsdummies/cache-service:a1.02
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: DATABASE
              value: mongodb://mongo:27017/user_auth
