version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/DSDUMMIES/cache # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - add_ssh_keys:
          fingerprints:
            - "76:5f:7a:bc:97:cb:e8:f6:01:10:05:52:38:43:95:89"

      - checkout: # check out source code to working directory
          path: ~/DSDUMMIES

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Success
          when: on_success
          command: |
            docker --version
            docker login -u dsdummies -p dsdummies3
            docker build -t dsdummies/cache-service:1.02 .
            docker push dsdummies/cache-service:1.02
            ssh -oStrictHostKeyChecking=no umangmsharma@149.165.156.154 -q <<'EOL'
              sudo su -
              cd DSDummies/kube
              kubectl delete -f cache-deployment.yaml
              kubectl apply -f cache-deployment.yaml
            EOL

      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building <application_name> $CIRCLE_BRANCH"
