version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/DSDUMMIES/Data-Ingestor # directory where steps will run

    docker: # run the steps with Docker
      - image: cimg/base:2021.04 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands
      - add_ssh_keys:
          fingerprints:
            - "4a:ae:30:f4:14:d0:a0:df:0b:d4:73:ff:2f:2a:ce:0d"
            
      - checkout: # check out source code to working directory
          path: ~/DSDUMMIES

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build Success
          when: on_success
          command: |
            docker --version
            docker login -u dsdummies -p dsdummies3
            docker build -t dsdummies/data-ingestor:1.0 .
            docker push dsdummies/data-ingestor:1.0
            ssh -oStrictHostKeyChecking=no umangmsharma@149.165.157.85 -q <<'EOL'
              sudo su -
              cd DSDummies/kube
              kubectl delete -f data-ingestor.yaml
              kubectl apply -f data-ingestor.yaml
              
              
      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building <application_name> $CIRCLE_BRANCH"
