name: nexrad-env
channels:
  - conda-forge
dependencies:
  - pip
  - siphon
  - matplotlib
  - cartopy
  - metpy
  - boto3
  - boto
  - numpy
  - xgboost
  - Flask==1.1.2
  - Flask-RESTful==0.3.8
  - gcc_linux-64
  - gxx_linux-64
  - ffmpeg
