name: UI_CI




on:

  push:

    branches: [ Frontend-CI ]

  pull_request:

    branches: [ Frontend-CI ]




jobs:

  build:



    runs-on: ubuntu-latest




    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js 

      uses: actions/setup-node@v2

      with:

        node-version: 14.x

        cache: 'npm'

        cache-dependency-path: Client   

    - run: npm install

      working-directory: ./Client 

    - run: npm install -g jest

      working-directory: ./Client 

    - run: npm test

      working-directory: ./Client 
